# Generated by Django 6.0 on 2025-12-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_is_approver_remove_user_lga_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default=1, help_text='Applicant full legal name', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CITIZEN', 'Citizen'), ('LGA_OFFICER', 'LGA Officer'), ('ADMIN', 'Administrator')], default='CITIZEN', help_text='System role (admin-managed)', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, help_text='Primary email address', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nin',
            field=models.CharField(blank=True, help_text='National Identification Number (optional)', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(db_index=True, help_text='User phone number', max_length=15, unique=True),
        ),
    ]
