# Generated by Django 6.0 on 2025-12-12 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_full_name_user_role_alter_user_email_and_more'),
        ('lgas', '0002_alter_lga_options_lga_created_at_alter_lga_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lga',
            field=models.ForeignKey(blank=True, help_text='Assigned LGA (required for LGA Officers)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='officers', to='lgas.lga'),
        ),
    ]
