# Generated by Django 6.0 on 2025-12-21 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_managers'),
        ('lgas', '0007_alter_lga_chairman_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nin_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='lga',
            field=models.ForeignKey(blank=True, help_text='Required when role is LGA Officer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='officers', to='lgas.lga'),
        ),
    ]
