# Generated by Django 6.0 on 2025-12-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgas', '0004_alter_lga_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='lga',
            name='chairman_signature',
            field=models.ImageField(blank=True, help_text='Signature of the Executive Chairman', null=True, upload_to='lga_signatures/chairman/'),
        ),
        migrations.AddField(
            model_name='lga',
            name='hlga_signature',
            field=models.ImageField(blank=True, help_text='Signature of the Head of Local Government Administration', null=True, upload_to='lga_signatures/hlga/'),
        ),
        migrations.AlterField(
            model_name='lga',
            name='code',
            field=models.CharField(blank=True, help_text='Official LGA short code (used for seals & numbering)', max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='lga',
            name='seal',
            field=models.ImageField(blank=True, help_text='Official Local Government seal used on certificates', null=True, upload_to='lga_seals/'),
        ),
        migrations.AlterField(
            model_name='lga',
            name='slug',
            field=models.SlugField(blank=True, help_text='Certificate-safe identifier (auto-generated)', max_length=150),
        ),
    ]
