# Generated by Django 6.0 on 2025-12-15 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lgas', '0006_alter_lga_chairman_signature_alter_lga_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('nin', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(default='Not Provided', max_length=100)),
                ('home_town', models.CharField(max_length=100)),
                ('family_compound', models.CharField(max_length=150)),
                ('father_name', models.CharField(max_length=150)),
                ('mother_name', models.CharField(max_length=150)),
                ('purpose', models.TextField()),
                ('passport_photo', models.ImageField(null=True, upload_to='passports/')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('PAID', 'Paid'), ('IN_REVIEW', 'In Review'), ('APPROVED', 'Approved'), ('WITHDRAWN', 'Withdrawn')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('certificate_number', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('certificate_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('lga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='lgas.lga')),
            ],
        ),
    ]
