# Generated by Django 6.0 on 2025-12-12 22:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lga',
            options={'ordering': ('name',), 'verbose_name': 'Local Government Area', 'verbose_name_plural': 'Local Government Areas'},
        ),
        migrations.AddField(
            model_name='lga',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date this LGA was created in the system'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lga',
            name='code',
            field=models.CharField(blank=True, help_text='Official LGA code (optional)', max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='lga',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Controls whether this LGA is selectable by applicants'),
        ),
        migrations.AlterField(
            model_name='lga',
            name='name',
            field=models.CharField(help_text='Official name of the Local Government Area', max_length=150, unique=True),
        ),
        migrations.AddIndex(
            model_name='lga',
            index=models.Index(fields=['is_active'], name='lgas_lga_is_acti_f2a023_idx'),
        ),
        migrations.AddIndex(
            model_name='lga',
            index=models.Index(fields=['name'], name='lgas_lga_name_d246b2_idx'),
        ),
    ]
