# Generated by Django 6.0 on 2025-12-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgas', '0002_alter_lga_options_lga_created_at_alter_lga_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lga',
            name='seal',
            field=models.ImageField(blank=True, help_text='Official LGA seal used on certificates', null=True, upload_to='lg_seals/'),
        ),
        migrations.AddField(
            model_name="lga",
            name="slug",
            field=models.SlugField(
             max_length=150,
            blank=True,
            db_index=True,
            ),
        ),
        migrations.AlterField(
            model_name='lga',
            name='code',
            field=models.CharField(blank=True, help_text='Optional official LGA short code', max_length=10, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='lga',
            index=models.Index(fields=['slug'], name='lgas_lga_slug_653fa6_idx'),
        ),
    ]
