# Generated by Django 6.0 on 2025-12-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgas', '0003_lga_seal_lga_slug_alter_lga_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lga',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-safe and certificate-safe identifier (auto-generated)', max_length=150),
        ),
    ]
