# Generated by Django 6.0 on 2025-12-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgas', '0005_lga_chairman_signature_lga_hlga_signature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lga',
            name='chairman_signature',
            field=models.ImageField(blank=True, help_text='Signature of the Executive Chairman', null=True, upload_to='lga/signatures/chairman/'),
        ),
        migrations.AlterField(
            model_name='lga',
            name='code',
            field=models.CharField(blank=True, help_text='Official LGA short code (used in numbering and references)', max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='lga',
            name='hlga_signature',
            field=models.ImageField(blank=True, help_text='Signature of the Head of Local Government Administration', null=True, upload_to='lga/signatures/hlga/'),
        ),
        migrations.AlterField(
            model_name='lga',
            name='seal',
            field=models.ImageField(blank=True, help_text='Official Local Government seal used on certificates', null=True, upload_to='lga/seals/'),
        ),
        migrations.AlterField(
            model_name='lga',
            name='slug',
            field=models.SlugField(blank=True, help_text='Certificate-safe identifier (auto-generated, stable)', max_length=150),
        ),
    ]
