# Generated by Django 6.0 on 2025-12-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgas', '0006_alter_lga_chairman_signature_alter_lga_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lga',
            name='chairman_signature',
            field=models.ImageField(blank=True, null=True, upload_to='lga/signatures/chairman/'),
        ),
        migrations.AlterField(
            model_name='lga',
            name='hlga_signature',
            field=models.ImageField(blank=True, null=True, upload_to='lga/signatures/hlga/'),
        ),
        migrations.AlterField(
            model_name='lga',
            name='seal',
            field=models.ImageField(blank=True, null=True, upload_to='lga/seals/'),
        ),
    ]
