# Generated by Django 6.0 on 2025-12-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_approver',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lga',
        ),
        migrations.AlterField(
            model_name='user',
            name='nin',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
